routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);
Route::get('/login', function () {
    return redirect('admin/login');
});
Route::get('/register',function () {
    return redirect('admin/login');
});

Route::post('logout', 'Auth\LoginController@logout');


Route::get('/', 'WebsiteController@index')->name('index');
Route::get('/index', 'WebsiteController@index')->name('index');
Route::get('/about-us', 'WebsiteController@aboutUs')->name('about.us');
Route::get('/news', 'WebsiteController@news')->name('news');
Route::get('/services', 'WebsiteController@services')->name('services');
Route::get('/car-cosmetics', 'WebsiteController@carCosmetics')->name('car.cosmetics');
Route::get('/foil-technology', 'WebsiteController@foilTechnology')->name('foil.technology');
Route::get('/rim-tire', 'WebsiteController@rimTire')->name('rim.tire');
Route::get('/voucher', 'WebsiteController@voucher')->name('voucher');
Route::get('/contact', 'WebsiteController@contact')->name('contact');
Route::get('/portfolio', 'WebsiteController@portfolio')->name('portfolio');



// Route::get('/product', 'WebsiteController@product')->name('product');

// Route::get('/contact',  'WebsiteController@contact')->name('contact');

// Route::get('/work',  'WebsiteController@work')->name('work');


// Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' =>'admin'], function () {
	Auth::routes();

	Route::get('/', function () {
    	return redirect('admin/products');
	});
	Route::get('/register',function () {
    	return redirect('admin/products');
	});

	

	Route::group(['middleware' => 'auth'], function () {
		Route::post('products/switchUpdate', 'ProductController@switchUpdate')->name('products.switchUpdate');
    	Route::resource('/products', 'ProductController');
    	Route::post('/product/updateStatus', 'ProductController@toggleStatus')->name('product.toggleStatus');
	});
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::get();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product;
        $product->title = $request->title;
        $product->short_description = $request->short_description;
        $product->description = $request->description;
        $product->category = $request->category;
        
        if ($request->file('image')) {
            $storage_path = 'public/images';
            $product->image = Storage::disk('local')->put($storage_path,$request->file('image'));
        }

        $product->save();
        return redirect()->route('products.index')->with('message', "Product added successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->title = $request->title;
        $product->short_description = $request->short_description;
        $product->description = $request->description;
        $product->category = $request->category;
        
        if ($request->file('image')) {
            Storage::disk('local')->delete($product->image);

            $storage_path = 'public/images';
            $product->image = Storage::disk('local')->put($storage_path,$request->file('image'));
        }

        $product->save();
        return redirect()->route('products.index')->with('message', "Product update successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $products = Product::find(request('ids'));
        $products->delete();
        return response()->noContent();
    }
    public function switchUpdate(Request $request)
    {
        $crop = Product::find($request->ids);
        if (empty($crop->is_active)) {
            $crop->is_active = 1;
        } else {
            $crop->is_active = 0;
        }
        $crop->save();
        return response()->noContent();
    }
}

resources/views/product/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Add Product</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('products.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data" id="add_product_form">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                        <label for="description">Image</label>
                        <input type="file" name="image" class="form-control" id="image" accept="image/x-png,image/gif,image/jpeg">
                    </div>
                    <div class="form-group">
                        <label for="short_description">Short Description</label>
                        <textarea name="short_description" class="form-control" id="short_description" rows="2"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" class="form-control" id="description" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select class="form-control" name="category" id="category">
                              <option value="">Select Category</option>  
                              <option value="APP / MUSIC">APP / MUSIC</option>  
                              <option value="VIDEO GAME" >VIDEO GAME</option>  
                              <option value="APP / MOBILE">APP / MOBILE</option>  
                              <option value="WEBSITE">WEBSITE</option>  
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('description');
        CKEDITOR.replace('short_description');
        $("#add_product_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                title: {
                    required: true
                },
                 description: {
                    required: function(textarea) {
                        CKEDITOR.instances[textarea.id].updateElement();
                        var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                        return editorcontent.length === 0;
                    }
                },
                short_description: {
                    required: function(textarea) {
                        CKEDITOR.instances[textarea.id].updateElement();
                        var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                        return editorcontent.length === 0;
                    }
                },
                image: {
                    required: true
                },
                category: {
                    required: true
                }

            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Title'])",
                },
                description: {
                    required: "@lang('validation.required',['attribute'=>'Description'])",
                },
                short_description: {
                    required: "@lang('validation.required',['attribute'=>'Short Description'])",
                },
                image: {
                    required: "@lang('validation.required',['attribute'=>'Image'])",
                },
                category: {
                    required: "@lang('validation.required',['attribute'=>'Category'])",
                }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Edit Product</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('products.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                <form action="{{ route('products.update',[$product->id]) }}" method="POST" enctype="multipart/form-data" id="edit_product_form">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ old('title', isset($product->title) ? $product->title : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">Image</label>
                        <input type="file" name="image" class="form-control" id="image" accept="image/x-png,image/gif,image/jpeg">
                        <br>
                        <a href="{{ asset(Storage::url($product->image)) }}" target="_blank">
                            <img src="{{ asset(Storage::url($product->image)) }}" alt="" height=100 width=100>
                        </a>
                    </div>
                    <div class="form-group">
                        <label for="short_description">Short Description</label>
                        <textarea name="short_description" class="form-control" id="short_description" rows="2">
                             {!! $product->short_description !!}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" class="form-control" id="description" rows="5">
                            {!! $product->description !!}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select class="form-control" name="category" id="category">
                              <option value="">Select Category</option>  
                              <option @if($product->category == "APP / MUSIC") selected @endif value="APP / MUSIC">APP / MUSIC</option>  
                              <option @if($product->category == "VIDEO GAME" ) selected @endif  value="VIDEO GAME" >VIDEO GAME</option>  
                              <option @if($product->category == "APP / MOBILE" ) selected @endif value="APP / MOBILE">APP / MOBILE</option>  
                              <option @if($product->category == "WEBSITE" ) selected @endif value="WEBSITE">WEBSITE</option>  
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('description');
        CKEDITOR.replace('short_description');
        $("#edit_product_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                title: {
                    required: true
                },
                 description: {
                    required: function(textarea) {
                        CKEDITOR.instances[textarea.id].updateElement();
                        var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                        return editorcontent.length === 0;
                    }
                },
                short_description: {
                    required: function(textarea) {
                        CKEDITOR.instances[textarea.id].updateElement();
                        var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                        return editorcontent.length === 0;
                    }
                },
                category: {
                    required: true
                }

            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Title'])",
                },
                description: {
                    required: "@lang('validation.required',['attribute'=>'Description'])",
                },
                short_description: {
                    required: "@lang('validation.required',['attribute'=>'Short Description'])",
                },
                image: {
                    required: "@lang('validation.required',['attribute'=>'Image'])",
                },
                category: {
                    required: "@lang('validation.required',['attribute'=>'Category'])",
                }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
@endsection

resources/views/product/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h4>Products Mgmt</h4>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('products.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add new product</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                @if (session('success'))
                <div class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ session('success') }}
                </div>
                @endif
                @if (session('error'))
                <div class="alert alert-dismissable alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ session('error') }}
                </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Short Description</th>
                                        <th>Image</th>
                                        <th>Category</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($products as $key => $product)
                                    <tr data-entry-id="{{ $product->id }}">
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $product->title ?? ''}}</td>
                                        <td>
                                            {!! $product->short_description !!}</td>
                                        <td>
                                            @if($product->image)
                                                <a href="{{ asset(Storage::url($product->image)) }}" target="_blank">
                                                    <img src="{{ asset(Storage::url($product->image)) }}" alt="" height=50 width=50>
                                                </a>
                                            @else
                                                '-'
                                            @endif
                                        </td>
                                        <td>{{ $product->category ?? ''}}</td>
                                        <td>
                                            @include('partials.switch', ['id'=>
                                            $product->id,'is_active'=>$product->is_active])
                                        </td>
                                        <td>@include('partials.actions', ['id' => $product->id])</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
@endsection

resources/views/product/view.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <br>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Blog Details</h2>
        </div>
        <div class="col-md-6">
            <div class="float-right">
                <a href="{{ route('blogs.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <br>
        <div class="col-md-12">
            <br><br>
            <div class="todo-title">
                <strong>Title: </strong> {{ $blog->title ?? ''}}
            </div>
            <br>
            <div class="todo-description">
                <strong>Description: </strong> {{ $blog->description ?? ''}}
            </div>
            <br>
        </div>
    </div>
</div>
@endsection